name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -i private_key.pem ec2-user@54.172.108.139 "rm -rf ~/servicio-web && mkdir ~/servicio-web"
          scp -i private_key.pem -r app/ ec2-user@54.172.108.139:~/servicio-web/
          ssh -i private_key.pem ec2-user@54.172.108.139 "cd ~/servicio-web && python3 -m pip install -r app/requirements.txt && nohup python3 app/main.py &"
