name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Add EC2 host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 98.81.235.62 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i private_key.pem ec2-user@98.81.235.62 "rm -rf ~/servidorweb && mkdir ~/servidorweb"
          scp -i private_key.pem -r app/ ec2-user@98.81.235.62:~/servidorweb/
          ssh -i private_key.pem ec2-user@98.81.235.62 "cd ~/servidorweb && python3 -m pip install -r app/requierements.txt && nohup python3 app/main.py --port=8081 &"
